version: '3.7'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
    - postgres_data:/var/lib/postgressql/data/
    ports:
    - 5432:5432
  web:
    build: .
    expose:
      - 8000
    command: python /usr/src/message/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    volumes:
      - .:/usr/src/message
    ports:
    - 8000:8000
    env_file: .env
    environment:
      - DEBUG=TRUE

  redis:
    image: "redis:latest"
    command: redis-server
    ports:
    - 6379:6379

  celery:
    build: .
    command: celery -A message worker -l info
    volumes:
      - ./web/message:/message
    depends_on:
      - redis
    env_file: .env
    environment:
      - DEBUG=TRUE

  celery-beat:
    build: .
    command: celery -A message beat -l info
    volumes:
      - ./web/message:/message
    depends_on:
      - redis
    env_file: .env
    environment:
      - DEBUG=TRUE

volumes:
  postgres_data: