# Generated by Django 3.1 on 2020-08-17 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postman',
            old_name='status',
            new_name='sent',
        ),
    ]
