# Generated by Django 3.1 on 2020-08-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0002_auto_20200817_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postman',
            name='sent',
            field=models.BooleanField(auto_created=True),
        ),
    ]
