# Generated by Django 3.1 on 2020-08-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0003_auto_20200818_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postman',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
